before:
  hooks:
    - go mod tidy


builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - 386
      - arm
      - arm64

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: 'arm'

    binary: ai-infra-guard
    main: cmd/cli/main.go

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    files:
      - README*
      - data/*
      - License.txt
checksum:
  algorithm: sha256